<?php

use CodeIgniter\Router\RouteCollection;

/** @var RouteCollection $routes */
$routes->get('/', 'Auth::login');
$routes->get('/login', 'Auth::login');
$routes->post('/login', 'Auth::doLogin');
$routes->get('/logout', 'Auth::logout');
$routes->get('/password/olvidada', 'PasswordResetController::olvidada');
$routes->post('/password/olvidada', 'PasswordResetController::enviarEnlace');
$routes->get('/password/reset/(:any)', 'PasswordResetController::reset/$1');
$routes->post('/password/reset/(:any)', 'PasswordResetController::cambiarPassword/$1');
$routes->get('/perfil', 'Perfil::index', ['filter' => 'auth']);
$routes->get('/perfil/editar', 'Perfil::editar', ['filter' => 'auth']);
$routes->post('/perfil/editar', 'Perfil::actualizar', ['filter' => 'auth']);
$routes->get('/perfil/cambiar-password', 'Perfil::password', ['filter' => 'auth']);
$routes->post('/perfil/cambiar-password', 'Perfil::cambiarPassword', ['filter' => 'auth']);
$routes->get('/dashboard', 'Dashboard::index', ['filter' => 'auth']);
$routes->get('/grupos', 'Grupos::index', ['filter' => 'auth']);
$routes->get('/grupos/nuevo', 'Grupos::new', ['filter' => 'auth']);
$routes->post('/grupos', 'Grupos::create', ['filter' => 'auth']);
$routes->get('/grupos/(:num)', 'Grupos::show/$1', ['filter' => 'auth']);
$routes->get('/grupos/(:num)/editar', 'Grupos::edit/$1', ['filter' => 'auth']);
$routes->get('/grupos/(:num)/balance', 'Grupos::balance/$1', ['filter' => 'auth']);
$routes->put('/grupos/(:num)', 'Grupos::update/$1', ['filter' => 'auth']);
$routes->delete('/grupos/(:num)', 'Grupos::delete/$1', ['filter' => 'auth']);
$routes->post('/grupos/(:num)/estado', 'Grupos::cambiarEstado/$1', ['filter' => 'auth']);
$routes->post('/grupos/(:num)/miembros', 'Grupos::agregarMiembro/$1', ['filter' => 'auth']);
$routes->post('/grupos/(:num)/miembros/(:num)/rol', 'Grupos::cambiarRol/$1/$2', ['filter' => 'auth']);
$routes->delete('/grupos/(:num)/miembros/(:num)', 'Grupos::quitarMiembro/$1/$2', ['filter' => 'auth']);
$routes->get('/gastos', 'Gastos::index', ['filter' => 'auth']);
$routes->get('/gastos/nuevo', 'Gastos::new', ['filter' => 'auth']);
$routes->get('/gastos/exportar-pdf', 'Gastos::exportarPdf', ['filter' => 'auth']);
$routes->get('/gastos/exportar-excel', 'Gastos::exportarExcel', ['filter' => 'auth']);
$routes->post('/gastos', 'Gastos::create', ['filter' => 'auth']);
$routes->get('/gastos/(:num)', 'Gastos::show/$1', ['filter' => 'auth']);
$routes->get('/gastos/(:num)/editar', 'Gastos::edit/$1', ['filter' => 'auth']);
$routes->put('/gastos/(:num)', 'Gastos::update/$1', ['filter' => 'auth']);
$routes->delete('/gastos/(:num)', 'Gastos::delete/$1', ['filter' => 'auth']);
$routes->get('/pagos', 'Pagos::index', ['filter' => 'auth']);
$routes->get('/pagos/nuevo', 'Pagos::new', ['filter' => 'auth']);
$routes->get('/pagos/exportar-pdf', 'Pagos::exportarPdf', ['filter' => 'auth']);
$routes->get('/pagos/exportar-excel', 'Pagos::exportarExcel', ['filter' => 'auth']);
$routes->post('/pagos', 'Pagos::create', ['filter' => 'auth']);
$routes->get('/pagos/(:num)', 'Pagos::show/$1', ['filter' => 'auth']);
$routes->get('/pagos/(:num)/editar', 'Pagos::edit/$1', ['filter' => 'auth']);
$routes->put('/pagos/(:num)', 'Pagos::update/$1', ['filter' => 'auth']);
$routes->delete('/pagos/(:num)', 'Pagos::delete/$1', ['filter' => 'auth']);
$routes->get('/usuarios', 'Usuarios::index', ['filter' => ['auth', 'admin']]);
$routes->get('/usuarios/nuevo', 'Usuarios::new', ['filter' => ['auth', 'admin']]);
$routes->post('/usuarios', 'Usuarios::create', ['filter' => ['auth', 'admin']]);
$routes->get('/usuarios/(:num)/editar', 'Usuarios::edit/$1', ['filter' => ['auth', 'admin']]);
$routes->put('/usuarios/(:num)', 'Usuarios::update/$1', ['filter' => ['auth', 'admin']]);
$routes->post('/usuarios/(:num)/password', 'Usuarios::password/$1', ['filter' => ['auth', 'admin']]);

$routes->get('/categorias', 'Categorias::index', ['filter' => ['auth', 'admin']]);
$routes->get('/categorias/nuevo', 'Categorias::new', ['filter' => ['auth', 'admin']]);
$routes->post('/categorias', 'Categorias::create', ['filter' => ['auth', 'admin']]);
$routes->get('/categorias/(:num)/editar', 'Categorias::edit/$1', ['filter' => ['auth', 'admin']]);
$routes->put('/categorias/(:num)', 'Categorias::update/$1', ['filter' => ['auth', 'admin']]);
$routes->post('/categorias/(:num)/toggle', 'Categorias::toggle/$1', ['filter' => ['auth', 'admin']]);
$routes->delete('/categorias/(:num)', 'Categorias::delete/$1', ['filter' => ['auth', 'admin']]);
$routes->get('/reportes', 'Reportes::index', ['filter' => 'auth']);
$routes->get('/reportes/exportar', 'Reportes::exportar', ['filter' => 'auth']);
$routes->get('/reportes/exportar-pdf', 'Reportes::exportarPdf', ['filter' => 'auth']);
$routes->get('/grupos/(:num)/reportes', 'Reportes::grupo/$1', ['filter' => 'auth']);
$routes->get('/gastos/(:num)/recibo', 'Gastos::recibo/$1', ['filter' => 'auth']);
$routes->delete('/gastos/(:num)/recibo', 'Gastos::deleteRecibo/$1', ['filter' => 'auth']);
$routes->get('/mis-medios-de-cobro', 'MediosCobro::index', ['filter' => 'auth']);
$routes->get('/mis-medios-de-cobro/nuevo', 'MediosCobro::new', ['filter' => 'auth']);
$routes->post('/mis-medios-de-cobro', 'MediosCobro::create', ['filter' => 'auth']);
$routes->get('/mis-medios-de-cobro/(:num)/editar', 'MediosCobro::edit/$1', ['filter' => 'auth']);
$routes->put('/mis-medios-de-cobro/(:num)', 'MediosCobro::update/$1', ['filter' => 'auth']);
$routes->post('/mis-medios-de-cobro/(:num)/toggle', 'MediosCobro::toggle/$1', ['filter' => 'auth']);
$routes->post('/mis-medios-de-cobro/(:num)/favorito', 'MediosCobro::favorito/$1', ['filter' => 'auth']);
$routes->delete('/mis-medios-de-cobro/(:num)', 'MediosCobro::delete/$1', ['filter' => 'auth']);

$routes->get('/doc', 'Documentacion::index');
$routes->get('/doc/(:any)', 'Documentacion::index/$1');
// Alias /documentacion -> /doc (si mod_dir no interfiere)
$routes->get('/documentacion', 'Documentacion::index');
$routes->get('/documentacion/(:any)', 'Documentacion::index/$1');
$routes->get('/admin/catalogo-tarjetas', 'Admin::catalogoTarjetas', ['filter' => ['auth', 'admin']]);
$routes->get('/admin/catalogo-tarjetas/(:segment)', 'Admin::catalogoTarjetas/$1', ['filter' => ['auth', 'admin']]);
$routes->post('/admin/catalogo-tarjetas/componente', 'Admin::guardarComponente', ['filter' => ['auth', 'admin']]);
$routes->post('/admin/catalogo-tarjetas/decision', 'Admin::guardarDecisionCatalogo', ['filter' => ['auth', 'admin']]);
$routes->post('/admin/catalogo-tarjetas/decision/limpiar', 'Admin::limpiarDecisionCatalogo', ['filter' => ['auth', 'admin']]);
$routes->post('/admin/catalogo-tarjetas/curaduria', 'Admin::guardarCuraduria', ['filter' => ['auth', 'admin']]);
$routes->post('/admin/catalogo-tarjetas/curaduria/limpiar', 'Admin::limpiarCuraduria', ['filter' => ['auth', 'admin']]);
