<?php

namespace Config;

class UiFeedback
{
    public const SLOT_DEFAULTS = [
        'feedback.success' => [
            'component' => 'alert_success',
            'variant' => 'success_compact',
        ],
        'feedback.error' => [
            'component' => 'alert_error',
            'variant' => 'error_action',
        ],
        'feedback.warning' => [
            'component' => 'alert_warning',
            'variant' => 'warning_debt',
        ],
        'feedback.info' => [
            'component' => 'alert_info',
            'variant' => 'info_filter',
        ],
        'confirmation.destructive' => [
            'component' => '_confirm_modal',
            'variant' => 'danger',
        ],
        'confirmation.warning' => [
            'component' => '_confirm_modal',
            'variant' => 'warning',
        ],
    ];

    public const ACTION_MAP = [
        'auth.login.failed' => [
            'slot' => 'feedback.error',
            'component' => 'alert_error',
            'variant' => 'error_action',
            'template' => 'Email o contraseña incorrectos.',
            'params' => [],
            'active' => true,
        ],
        'profile.update.completed' => [
            'slot' => 'feedback.success',
            'component' => 'alert_success',
            'variant' => 'settled',
            'template' => 'Perfil actualizado correctamente.',
            'params' => [],
            'active' => true,
        ],
        'profile.update.failed' => [
            'slot' => 'feedback.error',
            'component' => 'alert_error',
            'variant' => 'error_action',
            'template' => 'Error al actualizar el perfil. {reason}',
            'params' => ['reason'],
            'active' => true,
        ],
        'profile.password.change.completed' => [
            'slot' => 'feedback.success',
            'component' => 'alert_success',
            'variant' => 'synced',
            'template' => 'Contraseña actualizada correctamente.',
            'params' => [],
            'active' => true,
        ],
        'profile.password.change.failed' => [
            'slot' => 'feedback.error',
            'component' => 'alert_error',
            'variant' => 'error_action',
            'template' => 'No se pudo cambiar la contraseña. {reason}',
            'params' => ['reason'],
            'active' => true,
        ],
        'groups.create.completed' => [
            'slot' => 'feedback.success',
            'component' => 'alert_success',
            'variant' => 'settled',
            'template' => 'Grupo "{group_name}" creado correctamente.',
            'params' => ['group_name'],
            'active' => true,
        ],
        'groups.create.failed' => [
            'slot' => 'feedback.error',
            'component' => 'alert_error',
            'variant' => 'error_action',
            'template' => 'No se pudo crear el grupo. {reason}',
            'params' => ['reason'],
            'active' => true,
        ],
        'groups.update.completed' => [
            'slot' => 'feedback.success',
            'component' => 'alert_success',
            'variant' => 'settled',
            'template' => 'Grupo "{group_name}" actualizado correctamente.',
            'params' => ['group_name'],
            'active' => true,
        ],
        'groups.update.failed' => [
            'slot' => 'feedback.error',
            'component' => 'alert_error',
            'variant' => 'error_action',
            'template' => 'No se pudo actualizar el grupo. {reason}',
            'params' => ['reason'],
            'active' => true,
        ],
        'groups.delete.completed' => [
            'slot' => 'feedback.success',
            'component' => 'alert_success',
            'variant' => 'settled',
            'template' => 'Grupo eliminado correctamente.',
            'params' => [],
            'active' => true,
        ],
        'groups.delete.failed' => [
            'slot' => 'feedback.error',
            'component' => 'alert_error',
            'variant' => 'error_action',
            'template' => 'No se pudo eliminar el grupo. {reason}',
            'params' => ['reason'],
            'active' => true,
        ],
        'groups.close.completed' => [
            'slot' => 'feedback.success',
            'component' => 'alert_success',
            'variant' => 'settled',
            'template' => 'Grupo cerrado correctamente.',
            'params' => [],
            'active' => true,
        ],
        'groups.close.failed' => [
            'slot' => 'feedback.error',
            'component' => 'alert_error',
            'variant' => 'error_action',
            'template' => 'No se pudo cerrar el grupo. {reason}',
            'params' => ['reason'],
            'active' => true,
        ],
        'groups.reopen.completed' => [
            'slot' => 'feedback.success',
            'component' => 'alert_success',
            'variant' => 'settled',
            'template' => 'Grupo reabierto correctamente.',
            'params' => [],
            'active' => true,
        ],
        'groups.reopen.failed' => [
            'slot' => 'feedback.error',
            'component' => 'alert_error',
            'variant' => 'error_action',
            'template' => 'No se pudo reabrir el grupo. {reason}',
            'params' => ['reason'],
            'active' => true,
        ],
        'groups.liquidate.completed' => [
            'slot' => 'feedback.success',
            'component' => 'alert_success',
            'variant' => 'settled',
            'template' => 'Grupo liquidado correctamente.',
            'params' => [],
            'active' => true,
        ],
        'groups.liquidate.failed' => [
            'slot' => 'feedback.warning',
            'component' => 'alert_warning',
            'variant' => 'warning_debt',
            'template' => 'No se puede liquidar el grupo porque hay deudas pendientes.',
            'params' => [],
            'active' => true,
        ],
        'groups.member.add.completed' => [
            'slot' => 'feedback.success',
            'component' => 'alert_success',
            'variant' => 'member_added',
            'template' => 'Miembro agregado correctamente.',
            'params' => [],
            'active' => true,
        ],
        'groups.member.add.failed' => [
            'slot' => 'feedback.error',
            'component' => 'alert_error',
            'variant' => 'error_action',
            'template' => 'No se pudo agregar el miembro. {reason}',
            'params' => ['reason'],
            'active' => true,
        ],
        'groups.member.remove.completed' => [
            'slot' => 'feedback.success',
            'component' => 'alert_success',
            'variant' => 'settled',
            'template' => 'Miembro quitado correctamente.',
            'params' => [],
            'active' => true,
        ],
        'groups.member.remove.failed' => [
            'slot' => 'feedback.error',
            'component' => 'alert_error',
            'variant' => 'error_action',
            'template' => 'No se pudo quitar el miembro. {reason}',
            'params' => ['reason'],
            'active' => true,
        ],
    ];
}
