<?php

return [
    'title' => 'Alertas del sistema',
    'description' => 'Define el estilo base para mensajes de sistema, estados, errores y confirmaciones.',
    'screen' => 'system_alerts',
    'component' => 'system_alert_card',
    'selected' => $selectedSystemAlertVariant,
    'variants' => [
        require __DIR__ . '/variants/success_compact.php',
        require __DIR__ . '/variants/error_action.php',
        require __DIR__ . '/variants/warning_debt.php',
        require __DIR__ . '/variants/info_filter.php',
        require __DIR__ . '/variants/settled.php',
        require __DIR__ . '/variants/export_ready.php',
        require __DIR__ . '/variants/offline.php',
        require __DIR__ . '/variants/delete_confirmation.php',
        require __DIR__ . '/variants/suggested_payment.php',
        require __DIR__ . '/variants/update_available.php',
        require __DIR__ . '/variants/amount_validation.php',
        require __DIR__ . '/variants/out_of_period_date.php',
        require __DIR__ . '/variants/admin_permission.php',
        require __DIR__ . '/variants/favorite_updated.php',
        require __DIR__ . '/variants/import_ready.php',
        require __DIR__ . '/variants/import_partial.php',
        require __DIR__ . '/variants/settlement_recommendation.php',
        require __DIR__ . '/variants/empty_group.php',
        require __DIR__ . '/variants/empty_filter.php',
        require __DIR__ . '/variants/duplicate_payment.php',
        require __DIR__ . '/variants/session_expiring.php',
        require __DIR__ . '/variants/unsaved_changes.php',
        require __DIR__ . '/variants/heavy_report.php',
        require __DIR__ . '/variants/member_added.php',
        require __DIR__ . '/variants/member_removed.php',
        require __DIR__ . '/variants/balance_recalculated.php',
        require __DIR__ . '/variants/incomplete_payment_method.php',
        require __DIR__ . '/variants/backup_created.php',
        require __DIR__ . '/variants/synced.php',
        require __DIR__ . '/variants/maintenance.php',
    ],
];